Vagrant.configure("2") do |config|
	
	# Specify the base box
	config.vm.box = "ubuntu/trusty64"
config.vm.hostname="barona.dev"
config.vm.network "private_network", ip: "192.168.50.55"
config.ssh.insert_key = "true"
	# Setup port forwarding
	config.vm.network :forwarded_port, guest: 80, host: 8931, auto_correct: true

config.vm.synced_folder "./", "/var/www", :mount_options => ["dmode=777","fmode=666"]
    # Setup synced folder

	config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
end
    # Shell provisioning
    config.vm.provision "shell" do |s|
    	s.path = "provision/setup.sh"
    end
end